import type {Metadata} from "next";
import "./globals.css";
import '@unocss/reset/tailwind-compat.css'

import Upper from "@/app/_component/Upper";
import React from "react";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
            <div className={"w-full fixed top-0 left-0 bg-white pl-30px pr-67px pt-19px pb-14px"}>
                <Upper></Upper>
            </div>
            {children}
        </body>
        </html>
    );
}
